name = "MultiIndexing"
uuid = "b97ecbdf-1535-430e-a7c7-b5702749f368"
authors = ["Daniel Sharp <dannys4@mit.edu> and contributors"]
version = "1.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[extensions]
MultiIndexingKernelAbstractionsExt = "KernelAbstractions"

[compat]
StaticArrays = "1"
KernelAbstractions = "0.9"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
