name = "MultiIndexing"
uuid = "b97ecbdf-1535-430e-a7c7-b5702749f368"
authors = ["Daniel Sharp <dannys4@mit.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "Test"]
